# Generated by Django 5.2 on 2025-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_report_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(default='名無しのタイトル'),
        ),
    ]
